const ocrResponse3 = [
  {
    locations: [],
    properties: [],
    mid: '',
    locale: 'en',
    description:
      'FAIRPRICE FINEST\nHOUGANG A\nBlk 202 Hougang St 21 #01-00\nSingapore 530202\nTEL: 62870702\nREG No: RCS 1.1.191.1\nGST No: M4-0004578-0\nSGD\nFP ENR W/BR+25% 400G\nNTUCF/P.W/BR420+80G\n3X 1.35\nKF RED SPINACH 300G\nKF BABY SPINACH 300G\nLINK CARD 8105010000644217\nSUBTOTAL\nTOTAL\nMASTER\nACNT NO.############8378\nITEMS PURCHASED: 6\nGST Rate -- Before GST - GST Amt\n1.25\n1.65\n4.05\n1.50\n8.45\n8.45\n8.45',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 7, y: 13 },
        { x: 639, y: 13 },
        { x: 639, y: 1017 },
        { x: 7, y: 1017 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'FAIRPRICE',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 62, y: 17 },
        { x: 356, y: 17 },
        { x: 356, y: 51 },
        { x: 62, y: 51 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'FINEST',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 398, y: 17 },
        { x: 588, y: 17 },
        { x: 588, y: 51 },
        { x: 398, y: 51 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'HOUGANG',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 260, y: 68 },
        { x: 375, y: 67 },
        { x: 375, y: 96 },
        { x: 260, y: 97 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'A',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 393, y: 68 },
        { x: 411, y: 68 },
        { x: 411, y: 96 },
        { x: 393, y: 96 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Blk',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 110, y: 112 },
        { x: 161, y: 112 },
        { x: 161, y: 149 },
        { x: 110, y: 149 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '202',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 177, y: 112 },
        { x: 227, y: 112 },
        { x: 227, y: 148 },
        { x: 177, y: 148 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Hougang',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 245, y: 111 },
        { x: 359, y: 110 },
        { x: 359, y: 147 },
        { x: 245, y: 148 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'St',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 376, y: 110 },
        { x: 405, y: 110 },
        { x: 405, y: 147 },
        { x: 376, y: 147 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '21',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 424, y: 110 },
        { x: 458, y: 110 },
        { x: 458, y: 146 },
        { x: 424, y: 146 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '#',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 477, y: 110 },
        { x: 491, y: 110 },
        { x: 491, y: 146 },
        { x: 477, y: 146 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '01-00',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 491, y: 109 },
        { x: 574, y: 108 },
        { x: 574, y: 145 },
        { x: 491, y: 146 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Singapore',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 211, y: 160 },
        { x: 358, y: 158 },
        { x: 359, y: 192 },
        { x: 212, y: 195 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '530202',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 375, y: 157 },
        { x: 475, y: 155 },
        { x: 476, y: 190 },
        { x: 376, y: 192 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'TEL',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 229, y: 206 },
        { x: 276, y: 205 },
        { x: 277, y: 236 },
        { x: 230, y: 237 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 279, y: 205 },
        { x: 289, y: 205 },
        { x: 290, y: 235 },
        { x: 280, y: 235 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '62870702',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 309, y: 204 },
        { x: 440, y: 201 },
        { x: 441, y: 232 },
        { x: 310, y: 235 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'REG',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 164, y: 294 },
        { x: 212, y: 294 },
        { x: 212, y: 326 },
        { x: 164, y: 326 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'No',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 231, y: 294 },
        { x: 261, y: 294 },
        { x: 261, y: 325 },
        { x: 231, y: 325 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 268, y: 294 },
        { x: 277, y: 294 },
        { x: 277, y: 325 },
        { x: 268, y: 325 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'RCS',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 295, y: 293 },
        { x: 343, y: 293 },
        { x: 343, y: 324 },
        { x: 295, y: 324 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '1.1.191.1',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 363, y: 292 },
        { x: 506, y: 291 },
        { x: 506, y: 323 },
        { x: 363, y: 324 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GST',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 182, y: 341 },
        { x: 231, y: 341 },
        { x: 231, y: 372 },
        { x: 182, y: 372 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'No',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 248, y: 341 },
        { x: 278, y: 341 },
        { x: 278, y: 371 },
        { x: 248, y: 371 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 284, y: 341 },
        { x: 292, y: 341 },
        { x: 292, y: 371 },
        { x: 284, y: 371 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'M4-0004578-0',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 313, y: 340 },
        { x: 507, y: 339 },
        { x: 507, y: 370 },
        { x: 313, y: 371 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'SGD',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 508, y: 387 },
        { x: 561, y: 387 },
        { x: 561, y: 416 },
        { x: 508, y: 416 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'FP',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 7, y: 434 },
        { x: 38, y: 434 },
        { x: 38, y: 466 },
        { x: 7, y: 466 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'ENR',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 56, y: 434 },
        { x: 105, y: 434 },
        { x: 105, y: 465 },
        { x: 56, y: 465 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'W',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 117, y: 434 },
        { x: 135, y: 434 },
        { x: 135, y: 465 },
        { x: 117, y: 465 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '/',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 136, y: 433 },
        { x: 151, y: 433 },
        { x: 151, y: 464 },
        { x: 136, y: 464 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'BR',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 151, y: 433 },
        { x: 184, y: 433 },
        { x: 184, y: 464 },
        { x: 151, y: 464 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '+',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 184, y: 433 },
        { x: 197, y: 433 },
        { x: 197, y: 464 },
        { x: 184, y: 464 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '25',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 199, y: 433 },
        { x: 232, y: 433 },
        { x: 232, y: 464 },
        { x: 199, y: 464 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '%',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 231, y: 433 },
        { x: 249, y: 433 },
        { x: 249, y: 464 },
        { x: 231, y: 464 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '400G',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 263, y: 432 },
        { x: 328, y: 431 },
        { x: 328, y: 462 },
        { x: 263, y: 463 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'NTUCF',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 11, y: 479 },
        { x: 88, y: 479 },
        { x: 88, y: 512 },
        { x: 11, y: 512 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '/',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 90, y: 479 },
        { x: 103, y: 479 },
        { x: 103, y: 511 },
        { x: 90, y: 511 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'P.W',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 105, y: 479 },
        { x: 152, y: 479 },
        { x: 152, y: 511 },
        { x: 105, y: 511 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '/',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 154, y: 479 },
        { x: 167, y: 479 },
        { x: 167, y: 511 },
        { x: 154, y: 511 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'BR420',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 169, y: 478 },
        { x: 248, y: 478 },
        { x: 248, y: 511 },
        { x: 169, y: 511 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '+',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 249, y: 478 },
        { x: 264, y: 478 },
        { x: 264, y: 510 },
        { x: 249, y: 510 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '80G',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 266, y: 478 },
        { x: 315, y: 478 },
        { x: 315, y: 510 },
        { x: 266, y: 510 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '3X',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 11, y: 523 },
        { x: 44, y: 523 },
        { x: 44, y: 551 },
        { x: 11, y: 551 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '1.35',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 61, y: 523 },
        { x: 123, y: 523 },
        { x: 123, y: 551 },
        { x: 61, y: 551 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'KF',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 15, y: 566 },
        { x: 46, y: 566 },
        { x: 46, y: 596 },
        { x: 15, y: 596 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'RED',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 60, y: 566 },
        { x: 108, y: 566 },
        { x: 108, y: 595 },
        { x: 60, y: 595 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'SPINACH',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 124, y: 565 },
        { x: 235, y: 564 },
        { x: 235, y: 594 },
        { x: 124, y: 595 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '300G',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 251, y: 565 },
        { x: 314, y: 565 },
        { x: 314, y: 594 },
        { x: 251, y: 594 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'KF',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 16, y: 609 },
        { x: 48, y: 609 },
        { x: 48, y: 639 },
        { x: 16, y: 639 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'BABY',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 63, y: 609 },
        { x: 127, y: 609 },
        { x: 127, y: 638 },
        { x: 63, y: 638 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'SPINACH',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 142, y: 609 },
        { x: 253, y: 609 },
        { x: 253, y: 638 },
        { x: 142, y: 638 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '300G',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 268, y: 608 },
        { x: 332, y: 608 },
        { x: 332, y: 638 },
        { x: 268, y: 638 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'LINK',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 35, y: 651 },
        { x: 98, y: 651 },
        { x: 98, y: 680 },
        { x: 35, y: 680 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'CARD',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 113, y: 651 },
        { x: 177, y: 651 },
        { x: 177, y: 680 },
        { x: 113, y: 680 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '8105010000644217',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 222, y: 651 },
        { x: 475, y: 651 },
        { x: 475, y: 680 },
        { x: 222, y: 680 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'SUBTOTAL',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 82, y: 696 },
        { x: 206, y: 696 },
        { x: 206, y: 726 },
        { x: 82, y: 726 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'TOTAL',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 85, y: 782 },
        { x: 161, y: 782 },
        { x: 161, y: 809 },
        { x: 85, y: 809 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'MASTER',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 22, y: 824 },
        { x: 118, y: 823 },
        { x: 118, y: 853 },
        { x: 22, y: 854 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'ACNT',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 26, y: 867 },
        { x: 88, y: 868 },
        { x: 88, y: 897 },
        { x: 26, y: 896 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'NO',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 106, y: 867 },
        { x: 133, y: 867 },
        { x: 133, y: 896 },
        { x: 106, y: 896 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '.',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 142, y: 868 },
        { x: 142, y: 868 },
        { x: 142, y: 897 },
        { x: 142, y: 897 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '############',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 148, y: 867 },
        { x: 336, y: 869 },
        { x: 336, y: 899 },
        { x: 148, y: 897 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '8378',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 338, y: 869 },
        { x: 398, y: 870 },
        { x: 398, y: 900 },
        { x: 338, y: 899 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'ITEMS',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 93, y: 946 },
        { x: 166, y: 946 },
        { x: 166, y: 975 },
        { x: 93, y: 975 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'PURCHASED',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 183, y: 946 },
        { x: 322, y: 945 },
        { x: 322, y: 973 },
        { x: 183, y: 974 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 328, y: 945 },
        { x: 335, y: 945 },
        { x: 335, y: 973 },
        { x: 328, y: 973 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '6',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 354, y: 945 },
        { x: 370, y: 945 },
        { x: 370, y: 973 },
        { x: 354, y: 973 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GST',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 33, y: 987 },
        { x: 79, y: 986 },
        { x: 79, y: 1016 },
        { x: 33, y: 1017 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Rate',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 138, y: 986 },
        { x: 199, y: 985 },
        { x: 199, y: 1015 },
        { x: 138, y: 1016 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '--',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 215, y: 985 },
        { x: 246, y: 985 },
        { x: 246, y: 1014 },
        { x: 215, y: 1014 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Before',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 262, y: 984 },
        { x: 353, y: 983 },
        { x: 353, y: 1013 },
        { x: 262, y: 1014 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GST',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 370, y: 983 },
        { x: 414, y: 982 },
        { x: 414, y: 1011 },
        { x: 370, y: 1012 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '-',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 430, y: 983 },
        { x: 446, y: 983 },
        { x: 446, y: 1012 },
        { x: 430, y: 1012 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GST',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 462, y: 982 },
        { x: 510, y: 981 },
        { x: 510, y: 1010 },
        { x: 462, y: 1011 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Amt',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 522, y: 981 },
        { x: 568, y: 980 },
        { x: 568, y: 1010 },
        { x: 522, y: 1011 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '1.25',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 573, y: 432 },
        { x: 637, y: 431 },
        { x: 637, y: 460 },
        { x: 573, y: 461 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '1.65',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 574, y: 475 },
        { x: 636, y: 475 },
        { x: 636, y: 504 },
        { x: 574, y: 504 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '4.05',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 568, y: 566 },
        { x: 636, y: 566 },
        { x: 636, y: 591 },
        { x: 568, y: 591 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '1.50',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 573, y: 607 },
        { x: 633, y: 607 },
        { x: 633, y: 633 },
        { x: 573, y: 633 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '8.45',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 571, y: 693 },
        { x: 634, y: 693 },
        { x: 634, y: 721 },
        { x: 571, y: 721 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '8.45',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 571, y: 780 },
        { x: 633, y: 780 },
        { x: 633, y: 807 },
        { x: 571, y: 807 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '8.45',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 572, y: 823 },
        { x: 636, y: 822 },
        { x: 636, y: 851 },
        { x: 572, y: 852 },
      ],
      normalizedVertices: [],
    },
  },
];

export default ocrResponse3;
