const ocrResponse4 = [
  {
    locations: [],
    properties: [],
    mid: '',
    locale: 'en',
    description:
      "NTUC FAIRPRICE\nLOT 1 Shoppers' Mall\n21 Choa Chu Kang Ave 4\n#B1-03 Lot 1 Shoppers Mall S(689812)\nTEL: 67665009\nUEN No: S83CS0191L\nGST No: M4-0004578-0\n14.15\n2.65\n2.35\n2.55\n3.38\n3.05\n3.33\n2.97\n3.71\n1.90\n-0.35\n$39.69\n$0.45\n$15.00\n$30.00\n-$0.04\n$5.80\n***\n$5.10\n***\nRate After GST Tx Amn't\n***\n7.00%\n39.69\n2.60\n**\nCHONG SHI MIN\nRg:6\nCh:1139187\nCh:1139187 Tr:2348\n30/04/20\nBE BIO-R N/TON 100ML\nNormal Price 18.90\nGF OLD CUCUMBER\nM PORK L/MEAT 397G\nNZ ROYAL GALA APPLES\nPK FT SHOULDR BUTT\nPK FT SHOULDR BUTT\nPK FT SHOULDR BUTT\nPK FT SHOULDR BUTT\nPK FT SHOULDR BUTT\nUC XTR/SM/SILKEN300G\n2X$0.95/Unit\n2 FOR $1.55\nLINK CARD 8108000012628040\nTOTAL\nLINKPTS REDEMP\nFAIRPRICEVOUCHER\nCASH\nRounding\nChange\n********\n***\nTOTAL SAVINGS\n******\nDescription\nGST\n***\nTotal Items: 11\nSt: LOT1\nNo. of Bonus Stamp Issued = 1\n08:11\nThank You For Shopping With Us !\nKeep receipt for exchange or refund.\nSee in-store poster for details",
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 14, y: 300 },
        { x: 1887, y: 300 },
        { x: 1887, y: 3944 },
        { x: 14, y: 3944 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'NTUC',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 662, y: 304 },
        { x: 823, y: 306 },
        { x: 822, y: 366 },
        { x: 661, y: 364 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'FAIRPRICE',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 863, y: 307 },
        { x: 1221, y: 311 },
        { x: 1220, y: 370 },
        { x: 862, y: 366 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'LOT',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 538, y: 380 },
        { x: 657, y: 381 },
        { x: 657, y: 446 },
        { x: 538, y: 445 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '1',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 705, y: 382 },
        { x: 737, y: 382 },
        { x: 737, y: 446 },
        { x: 705, y: 446 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Shoppers',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 782, y: 382 },
        { x: 1102, y: 384 },
        { x: 1102, y: 449 },
        { x: 782, y: 447 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: "'",
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1117, y: 385 },
        { x: 1132, y: 385 },
        { x: 1132, y: 449 },
        { x: 1117, y: 449 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Mall',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1183, y: 385 },
        { x: 1332, y: 386 },
        { x: 1332, y: 451 },
        { x: 1183, y: 450 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '21',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 499, y: 452 },
        { x: 575, y: 453 },
        { x: 574, y: 518 },
        { x: 498, y: 517 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Choa',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 620, y: 454 },
        { x: 779, y: 457 },
        { x: 778, y: 522 },
        { x: 619, y: 519 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Chu',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 822, y: 458 },
        { x: 941, y: 460 },
        { x: 940, y: 525 },
        { x: 821, y: 523 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Kang',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 985, y: 462 },
        { x: 1142, y: 465 },
        { x: 1141, y: 529 },
        { x: 984, y: 526 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Ave',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1182, y: 465 },
        { x: 1302, y: 467 },
        { x: 1301, y: 532 },
        { x: 1181, y: 530 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '4',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1343, y: 469 },
        { x: 1384, y: 470 },
        { x: 1383, y: 534 },
        { x: 1342, y: 533 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '#',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 216, y: 520 },
        { x: 248, y: 521 },
        { x: 247, y: 585 },
        { x: 215, y: 584 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'B1-03',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 254, y: 520 },
        { x: 453, y: 524 },
        { x: 452, y: 588 },
        { x: 253, y: 584 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Lot',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 499, y: 524 },
        { x: 612, y: 526 },
        { x: 611, y: 591 },
        { x: 498, y: 589 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '1',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 664, y: 528 },
        { x: 696, y: 529 },
        { x: 695, y: 593 },
        { x: 663, y: 592 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Shoppers',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 743, y: 529 },
        { x: 1058, y: 535 },
        { x: 1057, y: 599 },
        { x: 742, y: 593 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Mall',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1104, y: 535 },
        { x: 1252, y: 538 },
        { x: 1251, y: 603 },
        { x: 1103, y: 600 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'S',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1305, y: 539 },
        { x: 1340, y: 540 },
        { x: 1339, y: 604 },
        { x: 1304, y: 603 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '(',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1351, y: 540 },
        { x: 1377, y: 540 },
        { x: 1376, y: 604 },
        { x: 1350, y: 604 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '689812',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1385, y: 540 },
        { x: 1619, y: 544 },
        { x: 1618, y: 609 },
        { x: 1384, y: 605 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ')',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1627, y: 545 },
        { x: 1652, y: 545 },
        { x: 1651, y: 609 },
        { x: 1626, y: 609 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'TEL',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 660, y: 606 },
        { x: 778, y: 607 },
        { x: 777, y: 670 },
        { x: 659, y: 669 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 796, y: 608 },
        { x: 812, y: 608 },
        { x: 811, y: 670 },
        { x: 795, y: 670 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '67665009',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 865, y: 609 },
        { x: 1186, y: 613 },
        { x: 1185, y: 675 },
        { x: 864, y: 671 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'UEN',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 580, y: 755 },
        { x: 702, y: 757 },
        { x: 701, y: 818 },
        { x: 579, y: 816 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'No',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 743, y: 757 },
        { x: 822, y: 758 },
        { x: 821, y: 819 },
        { x: 742, y: 818 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 836, y: 759 },
        { x: 856, y: 759 },
        { x: 855, y: 819 },
        { x: 835, y: 819 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'S83CS0191L',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 904, y: 759 },
        { x: 1307, y: 764 },
        { x: 1306, y: 825 },
        { x: 903, y: 820 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GST',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 538, y: 834 },
        { x: 658, y: 835 },
        { x: 657, y: 895 },
        { x: 537, y: 894 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'No',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 704, y: 836 },
        { x: 780, y: 837 },
        { x: 779, y: 897 },
        { x: 703, y: 896 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 795, y: 837 },
        { x: 814, y: 837 },
        { x: 813, y: 896 },
        { x: 794, y: 896 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'M4-0004578-0',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 865, y: 838 },
        { x: 1348, y: 843 },
        { x: 1347, y: 903 },
        { x: 864, y: 898 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '14.15',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1551, y: 1001 },
        { x: 1752, y: 995 },
        { x: 1753, y: 1048 },
        { x: 1553, y: 1054 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '2.65',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1591, y: 1150 },
        { x: 1758, y: 1150 },
        { x: 1758, y: 1211 },
        { x: 1591, y: 1211 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '2.35',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1591, y: 1233 },
        { x: 1756, y: 1233 },
        { x: 1756, y: 1288 },
        { x: 1591, y: 1288 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '2.55',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1587, y: 1312 },
        { x: 1756, y: 1310 },
        { x: 1757, y: 1366 },
        { x: 1588, y: 1368 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '3.38',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1590, y: 1391 },
        { x: 1752, y: 1391 },
        { x: 1752, y: 1448 },
        { x: 1590, y: 1448 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '3.05',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1588, y: 1468 },
        { x: 1750, y: 1467 },
        { x: 1750, y: 1525 },
        { x: 1588, y: 1526 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '3.33',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1589, y: 1550 },
        { x: 1749, y: 1550 },
        { x: 1749, y: 1600 },
        { x: 1589, y: 1600 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '2.97',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1587, y: 1624 },
        { x: 1754, y: 1621 },
        { x: 1755, y: 1676 },
        { x: 1588, y: 1679 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '3.71',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1592, y: 1697 },
        { x: 1756, y: 1696 },
        { x: 1756, y: 1751 },
        { x: 1592, y: 1752 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '1.90',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1598, y: 1851 },
        { x: 1758, y: 1849 },
        { x: 1759, y: 1905 },
        { x: 1599, y: 1907 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '-0.35',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1562, y: 1927 },
        { x: 1760, y: 1927 },
        { x: 1760, y: 1983 },
        { x: 1562, y: 1983 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '$',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1275, y: 2162 },
        { x: 1353, y: 2161 },
        { x: 1354, y: 2225 },
        { x: 1276, y: 2226 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '39.69',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1363, y: 2161 },
        { x: 1757, y: 2157 },
        { x: 1758, y: 2221 },
        { x: 1364, y: 2225 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '$',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1555, y: 2239 },
        { x: 1597, y: 2239 },
        { x: 1597, y: 2295 },
        { x: 1555, y: 2295 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '0.45',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1600, y: 2239 },
        { x: 1760, y: 2239 },
        { x: 1760, y: 2295 },
        { x: 1600, y: 2295 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '$',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1515, y: 2318 },
        { x: 1557, y: 2318 },
        { x: 1557, y: 2374 },
        { x: 1515, y: 2374 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '15.00',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1561, y: 2318 },
        { x: 1758, y: 2318 },
        { x: 1758, y: 2374 },
        { x: 1561, y: 2374 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '$',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1517, y: 2395 },
        { x: 1563, y: 2395 },
        { x: 1563, y: 2458 },
        { x: 1517, y: 2458 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '30.00',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1561, y: 2395 },
        { x: 1764, y: 2395 },
        { x: 1764, y: 2458 },
        { x: 1561, y: 2458 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '-',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1518, y: 2475 },
        { x: 1551, y: 2475 },
        { x: 1551, y: 2531 },
        { x: 1518, y: 2531 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '$',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1555, y: 2475 },
        { x: 1594, y: 2475 },
        { x: 1594, y: 2531 },
        { x: 1555, y: 2531 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '0.04',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1599, y: 2475 },
        { x: 1760, y: 2475 },
        { x: 1760, y: 2531 },
        { x: 1599, y: 2531 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '$',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1560, y: 2553 },
        { x: 1602, y: 2553 },
        { x: 1602, y: 2614 },
        { x: 1560, y: 2614 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '5.80',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1603, y: 2553 },
        { x: 1766, y: 2553 },
        { x: 1766, y: 2614 },
        { x: 1603, y: 2614 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '***',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1734, y: 2638 },
        { x: 1843, y: 2638 },
        { x: 1843, y: 2663 },
        { x: 1734, y: 2663 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '$',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1364, y: 2696 },
        { x: 1436, y: 2696 },
        { x: 1436, y: 2757 },
        { x: 1364, y: 2757 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '5.10',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1449, y: 2696 },
        { x: 1763, y: 2696 },
        { x: 1763, y: 2757 },
        { x: 1449, y: 2757 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '***',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1735, y: 2796 },
        { x: 1846, y: 2796 },
        { x: 1846, y: 2822 },
        { x: 1735, y: 2822 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Rate',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 705, y: 2942 },
        { x: 873, y: 2940 },
        { x: 874, y: 3011 },
        { x: 706, y: 3013 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'After',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1033, y: 2938 },
        { x: 1240, y: 2936 },
        { x: 1241, y: 3008 },
        { x: 1034, y: 3010 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GST',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1286, y: 2936 },
        { x: 1408, y: 2935 },
        { x: 1409, y: 3006 },
        { x: 1287, y: 3007 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Tx',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1488, y: 2933 },
        { x: 1575, y: 2932 },
        { x: 1576, y: 3004 },
        { x: 1489, y: 3005 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: "Amn't",
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1613, y: 2932 },
        { x: 1774, y: 2930 },
        { x: 1775, y: 3002 },
        { x: 1614, y: 3004 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '***',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1672, y: 3040 },
        { x: 1769, y: 3040 },
        { x: 1769, y: 3068 },
        { x: 1672, y: 3068 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '7.00',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 791, y: 3109 },
        { x: 951, y: 3109 },
        { x: 951, y: 3167 },
        { x: 791, y: 3167 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '%',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 953, y: 3109 },
        { x: 993, y: 3109 },
        { x: 993, y: 3167 },
        { x: 953, y: 3167 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '39.69',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1204, y: 3106 },
        { x: 1416, y: 3106 },
        { x: 1416, y: 3167 },
        { x: 1204, y: 3167 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '2.60',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1618, y: 3106 },
        { x: 1787, y: 3106 },
        { x: 1787, y: 3167 },
        { x: 1618, y: 3167 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '**',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1720, y: 3204 },
        { x: 1779, y: 3203 },
        { x: 1779, y: 3232 },
        { x: 1720, y: 3233 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'CHONG',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 662, y: 3362 },
        { x: 869, y: 3360 },
        { x: 870, y: 3422 },
        { x: 663, y: 3424 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'SHI',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 914, y: 3360 },
        { x: 1033, y: 3359 },
        { x: 1034, y: 3420 },
        { x: 915, y: 3421 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'MIN',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1083, y: 3358 },
        { x: 1207, y: 3357 },
        { x: 1208, y: 3419 },
        { x: 1084, y: 3420 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Rg',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 660, y: 3449 },
        { x: 749, y: 3447 },
        { x: 750, y: 3519 },
        { x: 661, y: 3521 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 756, y: 3447 },
        { x: 779, y: 3447 },
        { x: 780, y: 3519 },
        { x: 757, y: 3519 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '6',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 789, y: 3446 },
        { x: 833, y: 3445 },
        { x: 834, y: 3517 },
        { x: 790, y: 3518 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Ch',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 999, y: 3442 },
        { x: 1080, y: 3441 },
        { x: 1081, y: 3514 },
        { x: 1000, y: 3515 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1097, y: 3440 },
        { x: 1117, y: 3440 },
        { x: 1118, y: 3512 },
        { x: 1098, y: 3512 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '1139187',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1128, y: 3439 },
        { x: 1425, y: 3434 },
        { x: 1426, y: 3507 },
        { x: 1129, y: 3512 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Ch',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 999, y: 3444 },
        { x: 1083, y: 3443 },
        { x: 1084, y: 3511 },
        { x: 1000, y: 3512 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1097, y: 3444 },
        { x: 1119, y: 3444 },
        { x: 1120, y: 3511 },
        { x: 1098, y: 3511 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '1139187',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1128, y: 3443 },
        { x: 1426, y: 3440 },
        { x: 1427, y: 3508 },
        { x: 1129, y: 3511 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Tr',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1583, y: 3439 },
        { x: 1677, y: 3438 },
        { x: 1678, y: 3505 },
        { x: 1584, y: 3506 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1682, y: 3439 },
        { x: 1706, y: 3439 },
        { x: 1707, y: 3506 },
        { x: 1683, y: 3506 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '2348',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1713, y: 3438 },
        { x: 1885, y: 3437 },
        { x: 1886, y: 3504 },
        { x: 1714, y: 3506 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '30/04/20',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1001, y: 3531 },
        { x: 1336, y: 3528 },
        { x: 1337, y: 3586 },
        { x: 1002, y: 3589 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'BE',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 43, y: 981 },
        { x: 120, y: 982 },
        { x: 119, y: 1042 },
        { x: 42, y: 1041 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'BIO',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 168, y: 982 },
        { x: 292, y: 983 },
        { x: 291, y: 1043 },
        { x: 167, y: 1042 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '-',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 297, y: 983 },
        { x: 326, y: 983 },
        { x: 325, y: 1043 },
        { x: 296, y: 1043 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'R',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 334, y: 984 },
        { x: 370, y: 984 },
        { x: 369, y: 1044 },
        { x: 333, y: 1044 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'N',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 416, y: 985 },
        { x: 452, y: 985 },
        { x: 451, y: 1045 },
        { x: 415, y: 1045 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '/',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 461, y: 985 },
        { x: 496, y: 985 },
        { x: 495, y: 1045 },
        { x: 460, y: 1045 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'TON',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 497, y: 986 },
        { x: 617, y: 987 },
        { x: 616, y: 1047 },
        { x: 496, y: 1046 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '100ML',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 664, y: 987 },
        { x: 865, y: 989 },
        { x: 864, y: 1050 },
        { x: 663, y: 1048 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Normal',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 127, y: 1059 },
        { x: 361, y: 1063 },
        { x: 360, y: 1120 },
        { x: 126, y: 1116 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Price',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 414, y: 1064 },
        { x: 620, y: 1067 },
        { x: 619, y: 1124 },
        { x: 413, y: 1121 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '18.90',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 704, y: 1069 },
        { x: 901, y: 1072 },
        { x: 900, y: 1128 },
        { x: 703, y: 1125 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GF',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 46, y: 1141 },
        { x: 120, y: 1142 },
        { x: 119, y: 1199 },
        { x: 45, y: 1198 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'OLD',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 168, y: 1143 },
        { x: 289, y: 1145 },
        { x: 288, y: 1201 },
        { x: 167, y: 1199 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'CUCUMBER',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 333, y: 1145 },
        { x: 657, y: 1150 },
        { x: 656, y: 1207 },
        { x: 332, y: 1202 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'M',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 45, y: 1219 },
        { x: 85, y: 1219 },
        { x: 84, y: 1279 },
        { x: 44, y: 1279 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'PORK',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 127, y: 1219 },
        { x: 291, y: 1221 },
        { x: 290, y: 1282 },
        { x: 126, y: 1280 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'L',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 333, y: 1222 },
        { x: 372, y: 1222 },
        { x: 371, y: 1282 },
        { x: 332, y: 1282 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '/',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 373, y: 1223 },
        { x: 410, y: 1223 },
        { x: 409, y: 1283 },
        { x: 372, y: 1283 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'MEAT',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 414, y: 1223 },
        { x: 577, y: 1225 },
        { x: 576, y: 1285 },
        { x: 413, y: 1283 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '397G',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 619, y: 1225 },
        { x: 785, y: 1227 },
        { x: 784, y: 1288 },
        { x: 618, y: 1286 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'NZ',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 47, y: 1301 },
        { x: 126, y: 1302 },
        { x: 126, y: 1362 },
        { x: 47, y: 1361 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'ROYAL',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 169, y: 1301 },
        { x: 370, y: 1302 },
        { x: 370, y: 1363 },
        { x: 169, y: 1362 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GALA',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 417, y: 1303 },
        { x: 577, y: 1304 },
        { x: 577, y: 1365 },
        { x: 417, y: 1364 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'APPLES',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 618, y: 1304 },
        { x: 861, y: 1306 },
        { x: 861, y: 1367 },
        { x: 618, y: 1365 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'PK',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 46, y: 1381 },
        { x: 130, y: 1382 },
        { x: 129, y: 1442 },
        { x: 45, y: 1441 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'FT',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 172, y: 1382 },
        { x: 253, y: 1383 },
        { x: 252, y: 1443 },
        { x: 171, y: 1442 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'SHOULDR',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 296, y: 1383 },
        { x: 581, y: 1386 },
        { x: 580, y: 1446 },
        { x: 295, y: 1443 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'BUTT',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 623, y: 1386 },
        { x: 782, y: 1388 },
        { x: 781, y: 1449 },
        { x: 622, y: 1447 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'PK',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 47, y: 1462 },
        { x: 132, y: 1463 },
        { x: 132, y: 1521 },
        { x: 47, y: 1520 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'FT',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 172, y: 1462 },
        { x: 253, y: 1462 },
        { x: 253, y: 1521 },
        { x: 172, y: 1521 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'SHOULDR',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 297, y: 1463 },
        { x: 579, y: 1465 },
        { x: 579, y: 1524 },
        { x: 297, y: 1522 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'BUTT',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 623, y: 1465 },
        { x: 782, y: 1466 },
        { x: 782, y: 1524 },
        { x: 623, y: 1523 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'PK',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 48, y: 1540 },
        { x: 132, y: 1541 },
        { x: 132, y: 1597 },
        { x: 48, y: 1596 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'FT',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 173, y: 1540 },
        { x: 256, y: 1541 },
        { x: 256, y: 1598 },
        { x: 173, y: 1597 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'SHOULDR',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 300, y: 1541 },
        { x: 581, y: 1543 },
        { x: 581, y: 1600 },
        { x: 300, y: 1598 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'BUTT',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 625, y: 1543 },
        { x: 781, y: 1544 },
        { x: 781, y: 1601 },
        { x: 625, y: 1600 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'PK',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 47, y: 1613 },
        { x: 130, y: 1614 },
        { x: 130, y: 1669 },
        { x: 47, y: 1668 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'FT',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 173, y: 1613 },
        { x: 254, y: 1614 },
        { x: 254, y: 1670 },
        { x: 173, y: 1669 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'SHOULDR',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 299, y: 1614 },
        { x: 581, y: 1616 },
        { x: 581, y: 1672 },
        { x: 299, y: 1670 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'BUTT',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 625, y: 1616 },
        { x: 786, y: 1617 },
        { x: 786, y: 1673 },
        { x: 625, y: 1672 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'PK',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 48, y: 1692 },
        { x: 130, y: 1692 },
        { x: 130, y: 1750 },
        { x: 48, y: 1750 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'FT',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 172, y: 1692 },
        { x: 252, y: 1692 },
        { x: 252, y: 1750 },
        { x: 172, y: 1750 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'SHOULDR',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 297, y: 1692 },
        { x: 584, y: 1692 },
        { x: 584, y: 1750 },
        { x: 297, y: 1750 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'BUTT',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 626, y: 1692 },
        { x: 786, y: 1692 },
        { x: 786, y: 1750 },
        { x: 626, y: 1750 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'UC',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 46, y: 1769 },
        { x: 129, y: 1769 },
        { x: 129, y: 1826 },
        { x: 46, y: 1826 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'XTR',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 169, y: 1769 },
        { x: 291, y: 1769 },
        { x: 291, y: 1826 },
        { x: 169, y: 1826 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '/',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 299, y: 1769 },
        { x: 336, y: 1769 },
        { x: 336, y: 1826 },
        { x: 299, y: 1826 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'SM',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 338, y: 1769 },
        { x: 420, y: 1769 },
        { x: 420, y: 1826 },
        { x: 338, y: 1826 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '/',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 421, y: 1769 },
        { x: 458, y: 1769 },
        { x: 458, y: 1826 },
        { x: 421, y: 1826 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'SILKEN300G',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 460, y: 1769 },
        { x: 867, y: 1769 },
        { x: 867, y: 1826 },
        { x: 460, y: 1826 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '2X',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 45, y: 1848 },
        { x: 125, y: 1848 },
        { x: 125, y: 1907 },
        { x: 45, y: 1907 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '$',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 126, y: 1848 },
        { x: 165, y: 1848 },
        { x: 165, y: 1907 },
        { x: 126, y: 1907 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '0.95',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 171, y: 1848 },
        { x: 334, y: 1848 },
        { x: 334, y: 1907 },
        { x: 171, y: 1907 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '/',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 338, y: 1848 },
        { x: 378, y: 1848 },
        { x: 378, y: 1907 },
        { x: 338, y: 1907 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Unit',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 377, y: 1848 },
        { x: 542, y: 1848 },
        { x: 542, y: 1907 },
        { x: 377, y: 1907 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '2',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 125, y: 1924 },
        { x: 168, y: 1924 },
        { x: 168, y: 1980 },
        { x: 125, y: 1980 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'FOR',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 211, y: 1924 },
        { x: 333, y: 1924 },
        { x: 333, y: 1980 },
        { x: 211, y: 1980 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '$',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 375, y: 1924 },
        { x: 413, y: 1924 },
        { x: 413, y: 1980 },
        { x: 375, y: 1980 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '1.55',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 422, y: 1924 },
        { x: 581, y: 1924 },
        { x: 581, y: 1980 },
        { x: 422, y: 1980 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'LINK',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 42, y: 2004 },
        { x: 210, y: 2004 },
        { x: 210, y: 2065 },
        { x: 42, y: 2065 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'CARD',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 252, y: 2004 },
        { x: 418, y: 2004 },
        { x: 418, y: 2065 },
        { x: 252, y: 2065 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '8108000012628040',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 501, y: 2004 },
        { x: 1150, y: 2004 },
        { x: 1150, y: 2065 },
        { x: 501, y: 2065 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'TOTAL',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 52, y: 2162 },
        { x: 454, y: 2162 },
        { x: 454, y: 2221 },
        { x: 52, y: 2221 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'LINKPTS',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 45, y: 2241 },
        { x: 339, y: 2239 },
        { x: 339, y: 2297 },
        { x: 45, y: 2299 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'REDEMP',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 379, y: 2239 },
        { x: 623, y: 2237 },
        { x: 623, y: 2295 },
        { x: 379, y: 2297 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'FAIRPRICEVOUCHER',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 44, y: 2322 },
        { x: 702, y: 2316 },
        { x: 702, y: 2374 },
        { x: 45, y: 2380 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'CASH',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 46, y: 2403 },
        { x: 218, y: 2403 },
        { x: 218, y: 2461 },
        { x: 46, y: 2461 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Rounding',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 45, y: 2479 },
        { x: 373, y: 2478 },
        { x: 373, y: 2544 },
        { x: 45, y: 2545 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Change',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 46, y: 2563 },
        { x: 297, y: 2563 },
        { x: 297, y: 2622 },
        { x: 46, y: 2622 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '********',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 45, y: 2643 },
        { x: 366, y: 2639 },
        { x: 366, y: 2669 },
        { x: 45, y: 2673 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '***',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 833, y: 2635 },
        { x: 944, y: 2635 },
        { x: 944, y: 2665 },
        { x: 833, y: 2665 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'TOTAL',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 48, y: 2702 },
        { x: 454, y: 2700 },
        { x: 454, y: 2760 },
        { x: 48, y: 2762 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'SAVINGS',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 550, y: 2699 },
        { x: 1111, y: 2696 },
        { x: 1111, y: 2756 },
        { x: 550, y: 2759 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '******',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 46, y: 2803 },
        { x: 267, y: 2801 },
        { x: 267, y: 2828 },
        { x: 46, y: 2830 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Description',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 40, y: 2949 },
        { x: 498, y: 2944 },
        { x: 499, y: 3016 },
        { x: 41, y: 3021 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GST',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 32, y: 3117 },
        { x: 157, y: 3115 },
        { x: 158, y: 3176 },
        { x: 33, y: 3178 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '***',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 32, y: 3216 },
        { x: 150, y: 3215 },
        { x: 150, y: 3248 },
        { x: 32, y: 3249 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Total',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 28, y: 3285 },
        { x: 228, y: 3282 },
        { x: 229, y: 3346 },
        { x: 29, y: 3349 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Items',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 279, y: 3281 },
        { x: 487, y: 3278 },
        { x: 488, y: 3342 },
        { x: 280, y: 3345 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 505, y: 3278 },
        { x: 523, y: 3278 },
        { x: 524, y: 3341 },
        { x: 506, y: 3341 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '11',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 581, y: 3276 },
        { x: 659, y: 3275 },
        { x: 660, y: 3339 },
        { x: 582, y: 3340 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'St',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 23, y: 3457 },
        { x: 104, y: 3457 },
        { x: 104, y: 3519 },
        { x: 23, y: 3519 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 119, y: 3457 },
        { x: 138, y: 3457 },
        { x: 138, y: 3519 },
        { x: 119, y: 3519 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'LOT1',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 147, y: 3457 },
        { x: 318, y: 3457 },
        { x: 318, y: 3519 },
        { x: 147, y: 3519 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'No.',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 334, y: 2860 },
        { x: 449, y: 2859 },
        { x: 449, y: 2924 },
        { x: 334, y: 2925 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'of',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 498, y: 2859 },
        { x: 582, y: 2858 },
        { x: 582, y: 2922 },
        { x: 498, y: 2923 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Bonus',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 622, y: 2858 },
        { x: 830, y: 2857 },
        { x: 830, y: 2922 },
        { x: 622, y: 2923 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Stamp',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 873, y: 2857 },
        { x: 1071, y: 2856 },
        { x: 1071, y: 2921 },
        { x: 873, y: 2922 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Issued',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1120, y: 2855 },
        { x: 1363, y: 2853 },
        { x: 1363, y: 2918 },
        { x: 1120, y: 2920 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '=',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1410, y: 2854 },
        { x: 1442, y: 2854 },
        { x: 1442, y: 2918 },
        { x: 1410, y: 2918 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '1',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1489, y: 2853 },
        { x: 1525, y: 2853 },
        { x: 1525, y: 2917 },
        { x: 1489, y: 2917 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '08:11',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 575, y: 3533 },
        { x: 790, y: 3531 },
        { x: 791, y: 3599 },
        { x: 576, y: 3601 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Thank',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 275, y: 3708 },
        { x: 488, y: 3705 },
        { x: 489, y: 3780 },
        { x: 276, y: 3783 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'You',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 529, y: 3704 },
        { x: 656, y: 3702 },
        { x: 657, y: 3777 },
        { x: 530, y: 3779 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'For',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 701, y: 3702 },
        { x: 823, y: 3700 },
        { x: 824, y: 3774 },
        { x: 702, y: 3776 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Shopping',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 874, y: 3699 },
        { x: 1207, y: 3694 },
        { x: 1208, y: 3769 },
        { x: 875, y: 3774 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'With',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1252, y: 3693 },
        { x: 1415, y: 3690 },
        { x: 1416, y: 3765 },
        { x: 1253, y: 3768 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Us',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1461, y: 3690 },
        { x: 1545, y: 3689 },
        { x: 1546, y: 3763 },
        { x: 1462, y: 3764 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '!',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1593, y: 3688 },
        { x: 1617, y: 3688 },
        { x: 1618, y: 3762 },
        { x: 1594, y: 3762 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Keep',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 190, y: 3793 },
        { x: 359, y: 3790 },
        { x: 360, y: 3862 },
        { x: 191, y: 3865 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'receipt',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 405, y: 3789 },
        { x: 694, y: 3784 },
        { x: 695, y: 3856 },
        { x: 406, y: 3861 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'for',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 748, y: 3784 },
        { x: 862, y: 3782 },
        { x: 863, y: 3853 },
        { x: 749, y: 3855 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'exchange',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 917, y: 3781 },
        { x: 1250, y: 3775 },
        { x: 1251, y: 3846 },
        { x: 918, y: 3852 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'or',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1295, y: 3775 },
        { x: 1373, y: 3774 },
        { x: 1374, y: 3845 },
        { x: 1296, y: 3846 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'refund',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1420, y: 3772 },
        { x: 1666, y: 3768 },
        { x: 1667, y: 3840 },
        { x: 1421, y: 3844 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '.',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1681, y: 3768 },
        { x: 1706, y: 3768 },
        { x: 1707, y: 3839 },
        { x: 1682, y: 3839 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'See',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 279, y: 3868 },
        { x: 405, y: 3866 },
        { x: 406, y: 3941 },
        { x: 280, y: 3943 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'in',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 454, y: 3866 },
        { x: 528, y: 3865 },
        { x: 529, y: 3939 },
        { x: 455, y: 3940 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '-',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 535, y: 3864 },
        { x: 567, y: 3863 },
        { x: 568, y: 3937 },
        { x: 536, y: 3938 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'store',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 576, y: 3863 },
        { x: 786, y: 3860 },
        { x: 787, y: 3935 },
        { x: 577, y: 3938 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'poster',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 831, y: 3859 },
        { x: 1080, y: 3855 },
        { x: 1081, y: 3930 },
        { x: 832, y: 3934 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'for',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1133, y: 3855 },
        { x: 1247, y: 3853 },
        { x: 1248, y: 3927 },
        { x: 1134, y: 3929 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'details',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 1300, y: 3852 },
        { x: 1589, y: 3847 },
        { x: 1590, y: 3922 },
        { x: 1301, y: 3927 },
      ],
      normalizedVertices: [],
    },
  },
];

export default ocrResponse4;
