const ocrResponse2 = [
  {
    locations: [],
    properties: [],
    mid: '',
    locale: 'en',
    description:
      'NTUC FAIRPRICE\nGEYLANG\nLorong 3\n#612/620 Singapore 389551\nTEL: 6841-6016\nREG No: RCS 1.1.191.1\nGST No: M4-0004578-0\nSGD\n4.42\n4.65\n3.05\n2.70\n3.95\n1.43\n20.20\nUS BLACK GRAPES\nDranges\nMEIJI FRH MILK 830M\nMA.NSA PHRBERRIESIL\nG OG ROYAL GA_4 4S\nDELMCNTE BANANA\nSUBTOTAL\nTOTAL\n20.20\nMASTER\n20.20\nACNT NO.############4051\nITEMS PURCHASED: 6\nGST Rate Before GST- GST Amt\nSTAL\n90\n22',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 82, y: 4 },
        { x: 502, y: 4 },
        { x: 502, y: 608 },
        { x: 82, y: 608 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'NTUC',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 173, y: 14 },
        { x: 235, y: 12 },
        { x: 236, y: 34 },
        { x: 174, y: 36 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'FAIRPRICE',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 258, y: 11 },
        { x: 407, y: 6 },
        { x: 408, y: 28 },
        { x: 259, y: 33 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GEYLANG',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 265, y: 39 },
        { x: 323, y: 35 },
        { x: 324, y: 53 },
        { x: 266, y: 57 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Lorong',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 257, y: 62 },
        { x: 307, y: 60 },
        { x: 308, y: 79 },
        { x: 258, y: 81 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '3',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 316, y: 60 },
        { x: 325, y: 60 },
        { x: 326, y: 78 },
        { x: 317, y: 78 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '#',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 189, y: 84 },
        { x: 198, y: 84 },
        { x: 199, y: 104 },
        { x: 190, y: 104 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '612',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 196, y: 83 },
        { x: 222, y: 82 },
        { x: 223, y: 103 },
        { x: 197, y: 104 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '/',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 222, y: 82 },
        { x: 231, y: 82 },
        { x: 232, y: 102 },
        { x: 223, y: 102 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '620',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 232, y: 82 },
        { x: 257, y: 81 },
        { x: 258, y: 102 },
        { x: 233, y: 103 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Singapore',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 265, y: 81 },
        { x: 341, y: 79 },
        { x: 342, y: 100 },
        { x: 266, y: 102 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '389551',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 350, y: 78 },
        { x: 401, y: 76 },
        { x: 402, y: 97 },
        { x: 351, y: 99 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'TEL',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 242, y: 106 },
        { x: 265, y: 105 },
        { x: 266, y: 123 },
        { x: 243, y: 124 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 268, y: 105 },
        { x: 272, y: 105 },
        { x: 273, y: 122 },
        { x: 269, y: 122 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '6841-6016',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 283, y: 104 },
        { x: 360, y: 101 },
        { x: 361, y: 119 },
        { x: 284, y: 122 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'REG',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 206, y: 151 },
        { x: 231, y: 150 },
        { x: 231, y: 167 },
        { x: 206, y: 168 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'No',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 242, y: 151 },
        { x: 256, y: 151 },
        { x: 256, y: 167 },
        { x: 242, y: 167 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 261, y: 150 },
        { x: 265, y: 150 },
        { x: 265, y: 166 },
        { x: 261, y: 166 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'RCS',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 275, y: 150 },
        { x: 301, y: 149 },
        { x: 301, y: 165 },
        { x: 275, y: 166 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '1.1.191.1',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 311, y: 149 },
        { x: 387, y: 147 },
        { x: 387, y: 164 },
        { x: 311, y: 166 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GST',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 216, y: 174 },
        { x: 242, y: 174 },
        { x: 242, y: 192 },
        { x: 216, y: 192 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'No',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 250, y: 174 },
        { x: 265, y: 174 },
        { x: 265, y: 191 },
        { x: 250, y: 191 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 270, y: 174 },
        { x: 274, y: 174 },
        { x: 274, y: 191 },
        { x: 270, y: 191 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'M4-0004578-0',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 285, y: 173 },
        { x: 389, y: 171 },
        { x: 389, y: 189 },
        { x: 285, y: 191 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'SGD',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 391, y: 195 },
        { x: 418, y: 194 },
        { x: 419, y: 210 },
        { x: 392, y: 211 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '4.42',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 428, y: 213 },
        { x: 464, y: 211 },
        { x: 465, y: 223 },
        { x: 429, y: 225 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '4.65',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 432, y: 230 },
        { x: 469, y: 229 },
        { x: 469, y: 243 },
        { x: 433, y: 244 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '3.05',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 435, y: 252 },
        { x: 471, y: 252 },
        { x: 471, y: 266 },
        { x: 435, y: 266 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '2.70',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 437, y: 276 },
        { x: 474, y: 276 },
        { x: 474, y: 291 },
        { x: 437, y: 291 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '3.95',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 440, y: 300 },
        { x: 479, y: 300 },
        { x: 479, y: 316 },
        { x: 440, y: 316 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '1.43',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 444, y: 325 },
        { x: 481, y: 325 },
        { x: 481, y: 341 },
        { x: 444, y: 341 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '20.20',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 435, y: 352 },
        { x: 486, y: 352 },
        { x: 486, y: 367 },
        { x: 435, y: 367 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'US',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 116, y: 222 },
        { x: 133, y: 222 },
        { x: 133, y: 238 },
        { x: 116, y: 238 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'BLACK',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 141, y: 221 },
        { x: 187, y: 220 },
        { x: 187, y: 236 },
        { x: 141, y: 237 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GRAPES',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 195, y: 220 },
        { x: 249, y: 219 },
        { x: 249, y: 235 },
        { x: 195, y: 236 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Dranges',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 114, y: 245 },
        { x: 176, y: 243 },
        { x: 177, y: 258 },
        { x: 115, y: 260 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'MEIJI',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 112, y: 267 },
        { x: 157, y: 265 },
        { x: 158, y: 282 },
        { x: 113, y: 284 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'FRH',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 166, y: 264 },
        { x: 192, y: 263 },
        { x: 193, y: 280 },
        { x: 167, y: 281 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'MILK',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 202, y: 262 },
        { x: 239, y: 260 },
        { x: 240, y: 277 },
        { x: 203, y: 279 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '830M',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 258, y: 259 },
        { x: 295, y: 257 },
        { x: 296, y: 274 },
        { x: 259, y: 276 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'MA.NSA',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 111, y: 291 },
        { x: 165, y: 288 },
        { x: 166, y: 306 },
        { x: 112, y: 309 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'PHRBERRIESIL',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 173, y: 287 },
        { x: 286, y: 280 },
        { x: 287, y: 298 },
        { x: 174, y: 305 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'G',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 110, y: 315 },
        { x: 119, y: 315 },
        { x: 120, y: 332 },
        { x: 111, y: 332 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'OG',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 127, y: 314 },
        { x: 146, y: 313 },
        { x: 147, y: 330 },
        { x: 128, y: 331 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'ROYAL',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 155, y: 312 },
        { x: 200, y: 310 },
        { x: 201, y: 327 },
        { x: 156, y: 329 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GA_4',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 211, y: 309 },
        { x: 247, y: 307 },
        { x: 248, y: 325 },
        { x: 212, y: 327 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '4S',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 258, y: 307 },
        { x: 277, y: 306 },
        { x: 278, y: 323 },
        { x: 259, y: 324 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'DELMCNTE',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 107, y: 339 },
        { x: 181, y: 335 },
        { x: 182, y: 353 },
        { x: 108, y: 357 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'BANANA',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 210, y: 334 },
        { x: 268, y: 331 },
        { x: 269, y: 349 },
        { x: 211, y: 352 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'SUBTOTAL',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 144, y: 364 },
        { x: 219, y: 360 },
        { x: 220, y: 378 },
        { x: 145, y: 382 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'TOTAL',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 142, y: 416 },
        { x: 188, y: 414 },
        { x: 189, y: 433 },
        { x: 143, y: 435 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '20.20',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 441, y: 403 },
        { x: 493, y: 402 },
        { x: 493, y: 421 },
        { x: 441, y: 422 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'MASTER',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 99, y: 445 },
        { x: 162, y: 444 },
        { x: 162, y: 463 },
        { x: 99, y: 464 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '20.20',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 445, y: 432 },
        { x: 497, y: 431 },
        { x: 497, y: 449 },
        { x: 445, y: 450 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'ACNT',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 95, y: 473 },
        { x: 136, y: 472 },
        { x: 137, y: 494 },
        { x: 96, y: 495 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'NO',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 147, y: 471 },
        { x: 165, y: 470 },
        { x: 166, y: 492 },
        { x: 148, y: 493 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '.',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 171, y: 471 },
        { x: 175, y: 471 },
        { x: 176, y: 492 },
        { x: 172, y: 492 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '############',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 178, y: 470 },
        { x: 300, y: 466 },
        { x: 301, y: 488 },
        { x: 179, y: 492 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '4051',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 302, y: 466 },
        { x: 340, y: 465 },
        { x: 341, y: 487 },
        { x: 303, y: 488 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'ITEMS',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 134, y: 531 },
        { x: 184, y: 529 },
        { x: 185, y: 553 },
        { x: 135, y: 555 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'PURCHASED',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 196, y: 529 },
        { x: 292, y: 525 },
        { x: 293, y: 549 },
        { x: 197, y: 553 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: ':',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 296, y: 525 },
        { x: 301, y: 525 },
        { x: 302, y: 548 },
        { x: 297, y: 548 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '6',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 314, y: 525 },
        { x: 324, y: 525 },
        { x: 325, y: 548 },
        { x: 315, y: 548 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GST',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 91, y: 564 },
        { x: 124, y: 563 },
        { x: 125, y: 586 },
        { x: 92, y: 587 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Rate',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 165, y: 562 },
        { x: 207, y: 561 },
        { x: 208, y: 583 },
        { x: 166, y: 584 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Before',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 251, y: 559 },
        { x: 315, y: 557 },
        { x: 316, y: 580 },
        { x: 252, y: 582 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GST-',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 327, y: 557 },
        { x: 381, y: 555 },
        { x: 382, y: 577 },
        { x: 328, y: 579 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'GST',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 392, y: 555 },
        { x: 424, y: 554 },
        { x: 425, y: 576 },
        { x: 393, y: 577 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'Amt',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 436, y: 553 },
        { x: 469, y: 552 },
        { x: 470, y: 575 },
        { x: 437, y: 576 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: 'STAL',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 166, y: 594 },
        { x: 187, y: 594 },
        { x: 187, y: 599 },
        { x: 166, y: 599 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '90',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 318, y: 589 },
        { x: 337, y: 589 },
        { x: 337, y: 601 },
        { x: 318, y: 601 },
      ],
      normalizedVertices: [],
    },
  },
  {
    locations: [],
    properties: [],
    mid: '',
    locale: '',
    description: '22',
    score: 0,
    confidence: 0,
    topicality: 0,
    boundingPoly: {
      vertices: [
        { x: 418, y: 588 },
        { x: 438, y: 588 },
        { x: 438, y: 600 },
        { x: 418, y: 600 },
      ],
      normalizedVertices: [],
    },
  },
];

export default ocrResponse2;
